feat: выполнить ТЗ№10
elayhan/java-filmorate pull request #3
Opened 2023-03-28 15:17 UTC by elayhan

2023-03-29 14:40 UTC, VertigoMaker requested changes
По ТЗ всё верно

2023-03-29 14:40 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
Можно использовать final

2023-03-29 14:40 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        throw new NotFoundException("Нельзя обновить пользователя который не существует! Сначала создайте его.");
Рекомендую все ошибки catch`ить и писать в лог

2023-04-05 10:39 UTC, elayhan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
Нельзя

2023-04-05 10:40 UTC, elayhan commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        throw new NotFoundException("Нельзя обновить пользователя который не существует! Сначала создайте его.");
залогируем такие в ErrorHandler

2023-04-05 23:57 UTC, VertigoMaker approved these changes

2023-04-14 19:52 UTC, merged